Repository alvarlagerlof/neurodiversity, pull requests merged in 2021-05, with the labels that each got.

#25 Typo and grammar fixes
  README.md
  pages/index.js
  pages/ocd.mdx
Labels: content

#26 Minor spelling fixes
  components/blocks/PageLink.js
  pages/index.js
  pages/ocd.mdx
Labels: content

#16 Consistent indentation on ocd.mdx
  pages/ocd.mdx
Labels: enhancement

#19 Fix base path for preview deployments
  components/blocks/Meta.js
Labels: bug

#24 Custom plausible
  components/Plausible.js
  next.config.js
  pages/_app.js
  pages/index.js
Labels: enhancement

#34 Plausible fixes
  next.config.js
  pages/index.js
Labels: bug

#35 Upgrade to webpack 5
  next.config.js
Labels: enhancement
